# Supabase local config — vedi https://supabase.com/docs/guides/cli
project_id = "fppdfqieorixaduolnzn"

[db]
port = 54322
major_version = 15

[auth]
site_url = "http://localhost:3000"
additional_redirect_urls = [
  "http://localhost:3000/auth/callback",
  "https://my-immobiliaregestionale.vercel.app/auth/callback"
]
