import type { Plan } from "./types";

export const PLANS: Plan[] = [
  {
    id: "start",
    name: "Start",
    monthlyCents: 5900,
    setupCents: 49000,
    target: "Piccoli bar, take away, locali semplici",
    features: [
      "1 locale",
      "Fino a 30 ricette",
      "Fino a 100 ingredienti",
      "Food cost base",
      "Dashboard",
      "Report settimanale",
      "Caricamento fatture manuale",
      "1 utente titolare",
      "Supporto email",
    ],
    notIncluded: [
      "Report giornaliero",
      "Analisi menu avanzata",
      "Personale",
      "AI avanzata",
      "Consulenza mensile",
    ],
  },
  {
    id: "pro",
    name: "Pro",
    monthlyCents: 12900,
    setupCents: 99000,
    target: "Ristoranti, pizzerie, gelaterie, pasticcerie",
    highlighted: true,
    features: [
      "1 locale",
      "Fino a 100 ricette",
      "Ingredienti illimitati",
      "Food cost avanzato",
      "Menu engineering",
      "Report giornaliero",
      "Fatture fornitori",
      "Storico prezzi ingredienti",
      "Magazzino semplice",
      "Lista riordino",
      "Suggerimenti prezzo",
      "3 utenti",
      "Supporto prioritario",
    ],
  },
  {
    id: "premium",
    name: "Premium",
    monthlyCents: 24900,
    setupCents: 199000,
    target: "Locali strutturati, cucine complesse, più reparti",
    features: [
      "Tutto il piano Pro",
      "Fino a 10 utenti",
      "Report WhatsApp/Telegram",
      "Controllo personale",
      "Produzione giornaliera consigliata",
      "AI advisor",
      "Analisi menu mensile",
      "Confronto fornitori",
      "Report PDF mensile",
      "Call mensile di controllo",
      "Supporto prioritario",
    ],
  },
  {
    id: "enterprise",
    name: "Enterprise",
    monthlyCents: null,
    setupCents: null,
    target: "Catene, franchising, più punti vendita",
    features: [
      "Multi-sede",
      "Utenti illimitati",
      "Report direzionale",
      "Confronto tra sedi",
      "Controllo centrale",
      "Dashboard gruppo",
      "Account manager",
      "Integrazioni personalizzate",
    ],
  },
];

/** Compenso segnalatore semplice per piano venduto, in centesimi. */
export const REFERRAL_REWARDS_CENTS: Record<string, number> = {
  start: 5000,
  pro: 10000,
  premium: 20000,
};
