import type {
  BarberBooking,
  BarberCampaign,
  BarberCustomer,
  BarberPlan,
  BarberService,
} from "@deal-desk/types";

export const BARBER_DEMO_ORG_ID = "barber-demo-org";
export const BARBER_DEMO_ORG_NAME = "Atelier Barber Premium";

const today = new Date();

function atLocalTime(dayOffset: number, hour: number, minute = 0) {
  const date = new Date(today);
  date.setDate(today.getDate() + dayOffset);
  date.setHours(hour, minute, 0, 0);
  return date.toISOString();
}

export const demoServices: BarberService[] = [
  {
    id: "svc-signature",
    organization_id: BARBER_DEMO_ORG_ID,
    name: "Signature Cut",
    description: "Taglio premium con consulenza immagine, shampoo e styling finale.",
    duration_minutes: 45,
    price_cents: 4200,
    active: true,
    created_at: atLocalTime(-30, 9),
  },
  {
    id: "svc-beard",
    organization_id: BARBER_DEMO_ORG_ID,
    name: "Rituale Barba",
    description: "Panni caldi, modellatura, lama e trattamento nutriente.",
    duration_minutes: 30,
    price_cents: 2800,
    active: true,
    created_at: atLocalTime(-30, 9),
  },
  {
    id: "svc-combo",
    organization_id: BARBER_DEMO_ORG_ID,
    name: "Executive Combo",
    description: "Taglio, barba, trattamento cute e styling fotografico.",
    duration_minutes: 75,
    price_cents: 6800,
    active: true,
    created_at: atLocalTime(-30, 9),
  },
  {
    id: "svc-vip",
    organization_id: BARBER_DEMO_ORG_ID,
    name: "VIP Grooming Room",
    description: "Sessione privata con drink, consulenza look e priorita agenda.",
    duration_minutes: 90,
    price_cents: 12000,
    active: true,
    created_at: atLocalTime(-30, 9),
  },
];

export const demoCustomers: BarberCustomer[] = [
  {
    id: "cus-marco",
    organization_id: BARBER_DEMO_ORG_ID,
    full_name: "Marco Bellini",
    phone: "+39 333 111 2233",
    email: "marco@example.com",
    segment: "vip",
    referral_code: "MARCO20",
    referred_by_customer_id: null,
    total_spent_cents: 68400,
    visits_count: 14,
    last_visit_at: atLocalTime(-3, 17),
    notes: "Preferisce sfumatura bassa e appuntamento serale.",
    created_at: atLocalTime(-180, 10),
  },
  {
    id: "cus-luca",
    organization_id: BARBER_DEMO_ORG_ID,
    full_name: "Luca Ferri",
    phone: "+39 347 555 9191",
    email: "luca@example.com",
    segment: "regular",
    referral_code: "LUCA10",
    referred_by_customer_id: "cus-marco",
    total_spent_cents: 31200,
    visits_count: 7,
    last_visit_at: atLocalTime(-12, 12),
    notes: "Interessato a pacchetto barba mensile.",
    created_at: atLocalTime(-120, 11),
  },
  {
    id: "cus-andrea",
    organization_id: BARBER_DEMO_ORG_ID,
    full_name: "Andrea Russo",
    phone: "+39 320 778 4411",
    email: null,
    segment: "at_risk",
    referral_code: "ANDREA10",
    referred_by_customer_id: null,
    total_spent_cents: 9800,
    visits_count: 2,
    last_visit_at: atLocalTime(-76, 18),
    notes: "Inviare promo rientro.",
    created_at: atLocalTime(-220, 16),
  },
  {
    id: "cus-simone",
    organization_id: BARBER_DEMO_ORG_ID,
    full_name: "Simone Greco",
    phone: "+39 349 888 2010",
    email: "simone@example.com",
    segment: "referred",
    referral_code: "SIMONE10",
    referred_by_customer_id: "cus-luca",
    total_spent_cents: 6800,
    visits_count: 1,
    last_visit_at: atLocalTime(-1, 14),
    notes: "Nuovo cliente da referral.",
    created_at: atLocalTime(-7, 9),
  },
];

export const demoBookings: BarberBooking[] = [
  {
    id: "book-001",
    organization_id: BARBER_DEMO_ORG_ID,
    customer_id: "cus-marco",
    customer_name: "Marco Bellini",
    customer_phone: "+39 333 111 2233",
    service_id: "svc-vip",
    service_name: "VIP Grooming Room",
    starts_at: atLocalTime(0, 10),
    duration_minutes: 90,
    price_cents: 12000,
    status: "confirmed",
    referral_code: null,
    notes: "Preparare sala privata.",
    created_at: atLocalTime(-3, 11),
  },
  {
    id: "book-002",
    organization_id: BARBER_DEMO_ORG_ID,
    customer_id: "cus-luca",
    customer_name: "Luca Ferri",
    customer_phone: "+39 347 555 9191",
    service_id: "svc-combo",
    service_name: "Executive Combo",
    starts_at: atLocalTime(0, 12),
    duration_minutes: 75,
    price_cents: 6800,
    status: "confirmed",
    referral_code: "MARCO20",
    notes: null,
    created_at: atLocalTime(-2, 10),
  },
  {
    id: "book-003",
    organization_id: BARBER_DEMO_ORG_ID,
    customer_id: "cus-simone",
    customer_name: "Simone Greco",
    customer_phone: "+39 349 888 2010",
    service_id: "svc-signature",
    service_name: "Signature Cut",
    starts_at: atLocalTime(0, 16),
    duration_minutes: 45,
    price_cents: 4200,
    status: "completed",
    referral_code: "LUCA10",
    notes: null,
    created_at: atLocalTime(-1, 8),
  },
  {
    id: "book-004",
    organization_id: BARBER_DEMO_ORG_ID,
    customer_id: null,
    customer_name: "Davide Neri",
    customer_phone: "+39 338 121 9999",
    service_id: "svc-beard",
    service_name: "Rituale Barba",
    starts_at: atLocalTime(1, 11),
    duration_minutes: 30,
    price_cents: 2800,
    status: "requested",
    referral_code: null,
    notes: "Prima visita.",
    created_at: atLocalTime(0, 9),
  },
];

export const demoCampaigns: BarberCampaign[] = [
  {
    id: "camp-referral",
    organization_id: BARBER_DEMO_ORG_ID,
    name: "Porta un amico Gold",
    type: "referral",
    audience: "regular",
    incentive: "20% a entrambi sul prossimo Executive Combo",
    message: "Invita un amico: lui entra con il 20%, tu sblocchi un upgrade barba.",
    active: true,
    expected_redemptions: 18,
    revenue_target_cents: 122400,
    created_at: atLocalTime(-12, 9),
  },
  {
    id: "camp-reactivation",
    organization_id: BARBER_DEMO_ORG_ID,
    name: "Rientro clienti dormienti",
    type: "reactivation",
    audience: "at_risk",
    incentive: "Taglio Signature a 32 euro entro 10 giorni",
    message: "Ti aspetta un refresh premium: torna questa settimana e risparmia 10 euro.",
    active: true,
    expected_redemptions: 9,
    revenue_target_cents: 28800,
    created_at: atLocalTime(-5, 9),
  },
  {
    id: "camp-vip",
    organization_id: BARBER_DEMO_ORG_ID,
    name: "Upgrade VIP Room",
    type: "vip",
    audience: "vip",
    incentive: "Drink e trattamento cute incluso",
    message: "Accesso prioritario alla room privata per clienti top spender.",
    active: false,
    expected_redemptions: 6,
    revenue_target_cents: 72000,
    created_at: atLocalTime(-20, 9),
  },
];

export const barberPlans: BarberPlan[] = [
  {
    id: "basic",
    name: "Basic",
    tagline: "Per barbieri singoli che vogliono prenotazioni online.",
    monthly_price_cents: 2900,
    stripe_price_env: "STRIPE_PRICE_BASIC",
    highlighted: false,
    features: ["Agenda online", "Schede clienti", "Reminder manuali", "Dashboard incassi base"],
    limits: { seats: 1, monthly_bookings: 120, automations: 1 },
  },
  {
    id: "pro",
    name: "Pro",
    tagline: "Il piano consigliato per trasformare il salone in macchina ricorrente.",
    monthly_price_cents: 7900,
    stripe_price_env: "STRIPE_PRICE_PRO",
    highlighted: true,
    features: [
      "Prenotazioni illimitate",
      "Campagne sconto e porta un amico",
      "Segmenti clienti automatici",
      "Checkout Stripe",
      "Report incassi avanzato",
    ],
    limits: { seats: 4, monthly_bookings: null, automations: 8 },
  },
  {
    id: "elite",
    name: "Elite",
    tagline: "Per catene e barber shop premium con piu sedi.",
    monthly_price_cents: 19900,
    stripe_price_env: "STRIPE_PRICE_ELITE",
    highlighted: false,
    features: [
      "Multi-sede",
      "Ruoli staff",
      "Automazioni VIP",
      "Onboarding assistito",
      "Supporto prioritario",
    ],
    limits: { seats: 15, monthly_bookings: null, automations: 25 },
  },
];
